[death_messages]
	#Show death message for all entities. Silence individual entities using the 'deathfinder:silent_deaths' entity type tag.
	#Default Value: false
	all_deaths = false
	#Show death message for tamed entities.
	#Default Value: true
	pet_deaths = true
	#Show death message for named entities.
	#Default Value: true
	named_entity_deaths = true
	#Show death message for players.
	#Default Value: true
	player_deaths = true
	#Show death message for villagers.
	#Default Value: true
	villager_deaths = true

[death_message_components]
	#Add position component to death messages.
	#Default Value: true
	position_component = true
	#Who should be allowed to click the position component to teleport there.
	#Normal player can only teleport to their own death position once in a given time frame, if enabled.
	#Operators can teleport to any death position without limitations, if enabled.
	#Default Value: OPERATORS_ONLY
	#Allowed Values: NO_ONE, OPERATORS_ONLY, EVERYONE
	allow_teleporting = "OPERATORS_ONLY"
	#Add distance component to death messages.
	#Default Value: true
	distance_component = true
	#Add dimension component to death messages.
	#Default Value: true
	dimension_component = true
	#Amount of seconds in which teleporting to the last death point is possible.
	#Set to -1 to remove time limit.
	#Default Value: 300
	#Range: > -1
	teleport_interval = 300
